"""Install hints for new lanes and the missing-node_modules warning (decision 103, trial F3/F4)."""

import os
from pathlib import Path

import pytest

from helpers import write
from kitlib import lane_deps
from lane_helpers import PACKAGE_JSON


@pytest.fixture
def folder(tmp_path):
    path = tmp_path / "my lane" / "core"
    path.mkdir(parents=True)
    return path


# ---- install_hints -----------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("manifest", "lockfile", "command"),
    [
        ("package.json", "pnpm-lock.yaml", "pnpm install --frozen-lockfile"),
        ("package.json", "yarn.lock", "yarn install --immutable"),
        ("package.json", "package-lock.json", "npm ci"),
        ("package.json", "bun.lock", "bun install --frozen-lockfile"),
        ("package.json", "bun.lockb", "bun install --frozen-lockfile"),
        ("pyproject.toml", "uv.lock", "uv sync"),
        ("pyproject.toml", "poetry.lock", "poetry install"),
        ("Pipfile", "Pipfile.lock", "pipenv sync"),
        ("Gemfile", "Gemfile.lock", "bundle install"),
        ("composer.json", "composer.lock", "composer install"),
    ],
)
def test_each_lockfile_names_its_install_command(folder, manifest, lockfile, command):
    write(folder, manifest, "{}\n")
    write(folder, lockfile, "\n")
    assert lane_deps.install_hints(folder) == [command]


@pytest.mark.parametrize("manifest", ["package.json", "pyproject.toml", "requirements.txt", "Pipfile", "Gemfile"])
def test_a_manifest_without_a_lockfile_is_the_owners_call(folder, manifest):
    write(folder, manifest, "\n")
    assert lane_deps.install_hints(folder) == [f"the owner's call ({manifest} has no lockfile)"]


def test_no_manifest_says_nothing(folder):
    write(folder, "README.md", "# hi\n")
    assert lane_deps.install_hints(folder) == []


def test_a_lockfile_alone_still_names_the_command(folder):
    write(folder, "package-lock.json", "{}\n")
    assert lane_deps.install_hints(folder) == ["npm ci"]


def test_the_first_lockfile_in_the_table_wins(folder):
    # A project mid-migration keeps both; the survey's order says which tool it uses now.
    write(folder, "package.json", PACKAGE_JSON)
    write(folder, "package-lock.json", "{}\n")
    write(folder, "pnpm-lock.yaml", "\n")
    assert lane_deps.install_hints(folder) == ["pnpm install --frozen-lockfile"]


def test_yarn_1_lockfile_gets_yarn_1s_flag(folder):
    write(folder, "package.json", PACKAGE_JSON)
    write(folder, "yarn.lock", "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n")
    assert lane_deps.install_hints(folder) == ["yarn install --frozen-lockfile"]


def test_yarn_2_lockfile_gets_immutable(folder):
    write(folder, "package.json", PACKAGE_JSON)
    write(folder, "yarn.lock", '__metadata:\n  version: 8\n\n"left-pad@npm:1.3.0":\n')
    assert lane_deps.install_hints(folder) == ["yarn install --immutable"]


def test_two_ecosystems_get_a_line_each(folder):
    write(folder, "package.json", PACKAGE_JSON)
    write(folder, "yarn.lock", "\n")
    write(folder, "pyproject.toml", "\n")
    assert lane_deps.install_hints(folder) == [
        "yarn install --immutable",
        "the owner's call (pyproject.toml has no lockfile)",
    ]


def test_only_the_lane_root_is_read(folder):
    write(folder, "web/package.json", "{}\n")
    write(folder, "web/package-lock.json", "{}\n")
    assert lane_deps.install_hints(folder) == []


def test_a_folder_named_like_a_manifest_is_not_one(folder):
    (folder / "package.json").mkdir()
    assert lane_deps.install_hints(folder) == []
    assert lane_deps.missing_node_modules(folder, nested=True) is None


def test_a_folder_named_like_a_lockfile_is_not_one(folder):
    write(folder, "package.json", PACKAGE_JSON)
    (folder / "package-lock.json").mkdir()
    assert lane_deps.install_hints(folder) == ["the owner's call (package.json has no lockfile)"]


def test_windows_separators_in_the_folder(folder):
    write(folder, "package.json", PACKAGE_JSON)
    write(folder, "package-lock.json", "{}\n")
    assert lane_deps.install_hints(Path(str(folder).replace(os.sep, "/"))) == ["npm ci"]
    assert lane_deps.install_hints(str(folder)) == ["npm ci"]
    assert "npm ci" in lane_deps.missing_node_modules(str(folder), nested=True)


def test_uses_node(folder):
    assert not lane_deps.uses_node(folder)
    write(folder, "pnpm-lock.yaml", "\n")
    assert lane_deps.uses_node(folder)


# ---- missing_node_modules ----------------------------------------------------------------------


def test_nested_lane_without_node_modules_is_warned_about_the_main_checkout(folder):
    write(folder, "package.json", PACKAGE_JSON)
    write(folder, "package-lock.json", "{}\n")
    warning = lane_deps.missing_node_modules(folder, nested=True)
    assert "no node_modules" in warning and "npm ci" in warning and "main checkout" in warning
    assert lane_deps.missing_node_modules_short(folder) == "no node_modules (npm ci)"


def test_lane_outside_the_main_checkout_is_told_imports_fail(folder):
    write(folder, "package.json", PACKAGE_JSON)
    write(folder, "package-lock.json", "{}\n")
    warning = lane_deps.missing_node_modules(folder, nested=False)
    assert "npm ci" in warning and "main checkout" not in warning and "fail" in warning


def test_no_lockfile_warning_leaves_the_command_to_the_owner(folder):
    write(folder, "package.json", PACKAGE_JSON)
    assert "ask the owner" in lane_deps.missing_node_modules(folder, nested=True)
    assert lane_deps.missing_node_modules_short(folder) == "no node_modules (no lockfile: the owner picks the command)"


@pytest.mark.parametrize(
    "entry", ["express", ".package-lock.json", ".modules.yaml", ".yarn-state.yml", ".yarn-integrity"]
)
def test_installed_lane_is_not_warned(folder, entry):
    write(folder, "package.json", PACKAGE_JSON)
    (folder / "node_modules" / entry).mkdir(parents=True)
    assert lane_deps.missing_node_modules(folder, nested=True) is None
    assert lane_deps.missing_node_modules_short(folder) is None


@pytest.mark.parametrize("cache", [".vite", ".cache"])
def test_a_tools_cache_is_not_an_install(folder, cache):
    # Vite and babel-loader write here while running the main checkout's packages: still F4.
    write(folder, "package.json", PACKAGE_JSON)
    (folder / "node_modules" / cache).mkdir(parents=True)
    assert "no node_modules" in lane_deps.missing_node_modules(folder, nested=True)


def test_an_empty_node_modules_is_not_an_install(folder):
    write(folder, "package.json", PACKAGE_JSON)
    (folder / "node_modules").mkdir()
    assert lane_deps.missing_node_modules_short(folder) is not None


@pytest.mark.parametrize("pnp", [".pnp.cjs", ".pnp.js"])
def test_yarn_plug_and_play_needs_no_node_modules(folder, pnp):
    write(folder, "package.json", PACKAGE_JSON)
    write(folder, "yarn.lock", "\n")
    write(folder, pnp, "\n")
    assert lane_deps.missing_node_modules(folder, nested=True) is None


@pytest.mark.parametrize("text", ['{"name": "app", "scripts": {"start": "node x.js"}}\n', '{"dependencies": {}}\n'])
def test_a_package_json_without_packages_is_not_warned(folder, text):
    # npm installs nothing for these and makes no node_modules, so the warning could never clear.
    write(folder, "package.json", text)
    write(folder, "package-lock.json", "{}\n")
    assert lane_deps.missing_node_modules(folder, nested=True) is None


def test_a_pnpm_workspace_root_needs_an_install(folder):
    write(folder, "package.json", '{"scripts": {"build": "pnpm -r build"}}\n')
    write(folder, "pnpm-workspace.yaml", "packages:\n  - packages/*\n")
    write(folder, "pnpm-lock.yaml", "\n")
    assert lane_deps.missing_node_modules_short(folder) == "no node_modules (pnpm install --frozen-lockfile)"


@pytest.mark.parametrize("key", ["devDependencies", "optionalDependencies", "peerDependencies", "workspaces"])
def test_every_package_key_needs_an_install(folder, key):
    write(folder, "package.json", f'{{"{key}": {{"x": "1"}}}}\n')
    assert lane_deps.missing_node_modules_short(folder) is not None


@pytest.mark.parametrize("text", ["{ not json", "[]\n", "\xff\xfe"])
def test_a_package_json_that_doesnt_parse_still_warns(folder, text):
    (folder / "package.json").write_bytes(text.encode("latin-1"))
    assert lane_deps.missing_node_modules_short(folder) is not None


def test_no_package_json_is_not_warned(folder):
    write(folder, "pyproject.toml", "\n")
    assert lane_deps.missing_node_modules(folder, nested=True) is None
